# Form implementation generated from reading ui file 'AddCommandForm.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddButton(object):
    def setupUi(self, AddButton):
        AddButton.setObjectName("AddButton")
        AddButton.resize(400, 228)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddButton)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(AddButton)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(AddButton)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(AddButton)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(AddButton)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(AddButton)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(AddButton)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.AddCommandButton = QtWidgets.QPushButton(AddButton)
        self.AddCommandButton.setObjectName("AddCommandButton")
        self.verticalLayout.addWidget(self.AddCommandButton)

        self.retranslateUi(AddButton)
        QtCore.QMetaObject.connectSlotsByName(AddButton)

    def retranslateUi(self, AddButton):
        _translate = QtCore.QCoreApplication.translate
        AddButton.setWindowTitle(_translate("AddButton", "Добавление команды"))
        self.label.setText(_translate("AddButton", "Система команд"))
        self.label_2.setText(_translate("AddButton", "Название команды"))
        self.label_3.setText(_translate("AddButton", "Команда(Hex)"))
        self.AddCommandButton.setText(_translate("AddButton", "Добавить"))
