# Form implementation generated from reading ui file 'AddCommandOkDialog.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CommandAddDialog(object):
    def setupUi(self, CommandAddDialog):
        CommandAddDialog.setObjectName("CommandAddDialog")
        CommandAddDialog.resize(171, 113)
        CommandAddDialog.setWindowTitle("")
        self.verticalLayout = QtWidgets.QVBoxLayout(CommandAddDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(CommandAddDialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(CommandAddDialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(CommandAddDialog)
        QtCore.QMetaObject.connectSlotsByName(CommandAddDialog)

    def retranslateUi(self, CommandAddDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("CommandAddDialog", "Комманда добавленна"))
        self.pushButton.setText(_translate("CommandAddDialog", "ОК"))
