# Form implementation generated from reading ui file 'ChoiseComandForm.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ChoiseComandForm(object):
    def setupUi(self, ChoiseComandForm):
        ChoiseComandForm.setObjectName("ChoiseComandForm")
        ChoiseComandForm.resize(253, 269)
        self.verticalLayout = QtWidgets.QVBoxLayout(ChoiseComandForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ChoiseComandForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.systemsComboBox = QtWidgets.QComboBox(ChoiseComandForm)
        self.systemsComboBox.setObjectName("systemsComboBox")
        self.horizontalLayout.addWidget(self.systemsComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(ChoiseComandForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comandsComboBox = QtWidgets.QComboBox(ChoiseComandForm)
        self.comandsComboBox.setObjectName("comandsComboBox")
        self.horizontalLayout_2.addWidget(self.comandsComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.ChoiseButton = QtWidgets.QPushButton(ChoiseComandForm)
        self.ChoiseButton.setObjectName("ChoiseButton")
        self.verticalLayout.addWidget(self.ChoiseButton)

        self.retranslateUi(ChoiseComandForm)
        QtCore.QMetaObject.connectSlotsByName(ChoiseComandForm)

    def retranslateUi(self, ChoiseComandForm):
        _translate = QtCore.QCoreApplication.translate
        ChoiseComandForm.setWindowTitle(_translate("ChoiseComandForm", "Выбор команды"))
        self.label.setText(_translate("ChoiseComandForm", "Система команд"))
        self.label_2.setText(_translate("ChoiseComandForm", "Команда"))
        self.ChoiseButton.setText(_translate("ChoiseComandForm", "Выбрать"))
