# Form implementation generated from reading ui file 'DeleteComandForm.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteComandForm(object):
    def setupUi(self, DeleteComandForm):
        DeleteComandForm.setObjectName("DeleteComandForm")
        DeleteComandForm.resize(298, 162)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteComandForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DeleteComandForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.systemsComboBox = QtWidgets.QComboBox(DeleteComandForm)
        self.systemsComboBox.setObjectName("systemsComboBox")
        self.horizontalLayout.addWidget(self.systemsComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(DeleteComandForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comandsComboBox = QtWidgets.QComboBox(DeleteComandForm)
        self.comandsComboBox.setObjectName("comandsComboBox")
        self.horizontalLayout_2.addWidget(self.comandsComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.deleteButton = QtWidgets.QPushButton(DeleteComandForm)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)

        self.retranslateUi(DeleteComandForm)
        QtCore.QMetaObject.connectSlotsByName(DeleteComandForm)

    def retranslateUi(self, DeleteComandForm):
        _translate = QtCore.QCoreApplication.translate
        DeleteComandForm.setWindowTitle(_translate("DeleteComandForm", "Удаление команды"))
        self.label.setText(_translate("DeleteComandForm", "Система команд"))
        self.label_2.setText(_translate("DeleteComandForm", "Команда"))
        self.deleteButton.setText(_translate("DeleteComandForm", "Удалить"))
