# Form implementation generated from reading ui file 'RTUSettings.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RTUSettings(object):
    def setupUi(self, RTUSettings):
        RTUSettings.setObjectName("RTUSettings")
        RTUSettings.resize(291, 267)
        self.verticalLayout = QtWidgets.QVBoxLayout(RTUSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(RTUSettings)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(RTUSettings)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(RTUSettings)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 3, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(RTUSettings)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout.addWidget(self.comboBox_3, 4, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(RTUSettings)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(RTUSettings)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(RTUSettings)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(RTUSettings)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(RTUSettings)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(RTUSettings)
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.ConnectButton = QtWidgets.QPushButton(RTUSettings)
        self.ConnectButton.setObjectName("ConnectButton")
        self.verticalLayout.addWidget(self.ConnectButton)

        self.retranslateUi(RTUSettings)
        QtCore.QMetaObject.connectSlotsByName(RTUSettings)

    def retranslateUi(self, RTUSettings):
        _translate = QtCore.QCoreApplication.translate
        RTUSettings.setWindowTitle(_translate("RTUSettings", "Form"))
        self.label_4.setText(_translate("RTUSettings", "Стоп биты"))
        self.label_3.setText(_translate("RTUSettings", "Данные"))
        self.label.setText(_translate("RTUSettings", "Скорость(Бод)"))
        self.label_2.setText(_translate("RTUSettings", "Четность"))
        self.label_5.setText(_translate("RTUSettings", "Порт"))
        self.ConnectButton.setText(_translate("RTUSettings", "Подключиться"))
