# Form implementation generated from reading ui file 'TCPSettings.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TCPSettings(object):
    def setupUi(self, TCPSettings):
        TCPSettings.setObjectName("TCPSettings")
        TCPSettings.resize(250, 269)
        self.verticalLayout = QtWidgets.QVBoxLayout(TCPSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(TCPSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ip_edit = QtWidgets.QLineEdit(TCPSettings)
        self.ip_edit.setText("")
        self.ip_edit.setObjectName("ip_edit")
        self.horizontalLayout.addWidget(self.ip_edit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(TCPSettings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.port_edit = QtWidgets.QLineEdit(TCPSettings)
        self.port_edit.setText("")
        self.port_edit.setObjectName("port_edit")
        self.horizontalLayout_2.addWidget(self.port_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.connectButton = QtWidgets.QPushButton(TCPSettings)
        self.connectButton.setObjectName("connectButton")
        self.verticalLayout.addWidget(self.connectButton)

        self.retranslateUi(TCPSettings)
        QtCore.QMetaObject.connectSlotsByName(TCPSettings)

    def retranslateUi(self, TCPSettings):
        _translate = QtCore.QCoreApplication.translate
        TCPSettings.setWindowTitle(_translate("TCPSettings", "Настройки TCP"))
        self.label.setText(_translate("TCPSettings", "IP - Адрес"))
        self.ip_edit.setPlaceholderText(_translate("TCPSettings", "127.0.0.1"))
        self.label_2.setText(_translate("TCPSettings", "Порт"))
        self.port_edit.setPlaceholderText(_translate("TCPSettings", "0000"))
        self.connectButton.setText(_translate("TCPSettings", "Подключиться"))
