# Form implementation generated from reading ui file '.\uiSources\ErrConnectionNotEstablished.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectionNotEstablished(object):
    def setupUi(self, ConnectionError):
        ConnectionError.setObjectName("ConnectionError")
        ConnectionError.resize(355, 170)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=ConnectionError)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 331, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ConnectionError)
        self.buttonBox.setGeometry(QtCore.QRect(90, 130, 156, 24))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(ConnectionError)
        QtCore.QMetaObject.connectSlotsByName(ConnectionError)

    def retranslateUi(self, ConnectionError):
        _translate = QtCore.QCoreApplication.translate
        ConnectionError.setWindowTitle(_translate("ConnectionError", "Ошибка"))
        self.label.setText(_translate("ConnectionError", "<html><head/><body><p>Не установлено ни одного подключения (<span style=\" font-weight:700;\">RTU </span>или <span style=\" font-weight:700;\">TCP</span>). </p><p>Настройте подключение и повторите попытку.</p></body></html>"))
