# Form implementation generated from reading ui file 'EditComandForm.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditComandForm(object):
    def setupUi(self, EditComandForm):
        EditComandForm.setObjectName("EditComandForm")
        EditComandForm.resize(404, 268)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditComandForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(EditComandForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.systemsComboBox = QtWidgets.QComboBox(EditComandForm)
        self.systemsComboBox.setObjectName("systemsComboBox")
        self.horizontalLayout.addWidget(self.systemsComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(EditComandForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comandsComboBox = QtWidgets.QComboBox(EditComandForm)
        self.comandsComboBox.setObjectName("comandsComboBox")
        self.horizontalLayout_2.addWidget(self.comandsComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(EditComandForm)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comandValue = QtWidgets.QLineEdit(EditComandForm)
        self.comandValue.setObjectName("comandValue")
        self.horizontalLayout_3.addWidget(self.comandValue)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.editComandButton = QtWidgets.QPushButton(EditComandForm)
        self.editComandButton.setObjectName("editComandButton")
        self.verticalLayout.addWidget(self.editComandButton)

        self.retranslateUi(EditComandForm)
        QtCore.QMetaObject.connectSlotsByName(EditComandForm)

    def retranslateUi(self, EditComandForm):
        _translate = QtCore.QCoreApplication.translate
        EditComandForm.setWindowTitle(_translate("EditComandForm", "Изменить команду"))
        self.label.setText(_translate("EditComandForm", "Система команд"))
        self.label_2.setText(_translate("EditComandForm", "Команда"))
        self.label_3.setText(_translate("EditComandForm", "Значение"))
        self.editComandButton.setText(_translate("EditComandForm", "Изменить"))
